name: Add Labels

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: logto-io/actions-add-labels-run-steps@v1.0.1
        with:
          title: ${{ github.event.pull_request.title || github.event.issue.title }}
          github-token: ${{ github.token }}
